### ISSUE TITLE
Problem with downloading stories

### ISSUE THREAD

**Issue by the-gurk** [Moist-Cat/AIDScrapper#2]
Downloading stories from Ai Dungeon only downloads 25 stories when I have much more. These 25 stories seem to be the ones with the most actions. Using the -a command line argument doesn't change anything and using the -t command line argument loads stories but doesn't download them.

**Comment by Moist-Cat** [comment]
There was a problem with story validation. A blank title caused it to stop due to a poor design choice. I'm guessing that was the problem with the 26th story.

Upgrade to the last version and it should fix your issue.

    pip install -U aids

**Comment by the-gurk** [comment]
Thanks, that worked
