### ISSUE TITLE
Does it also have the feature to Obfuscate AI dungeon datas?

### ISSUE THREAD

**Issue by LAX-is-sleeping** [Moist-Cat/AIDScrapper#6]
I left my AI Dungeon account for a while and now i wanted to delete it, but i remember all the controversies too, so i wanted to delete it using this client. But i got concerned when i heard AIDcat is stopped its support, i knew i shouldn't trust Latitude with my data. Does this also have the feature to obfuscate AI dungeon data? thank you,

**Comment by Moist-Cat** [comment]
no
https://github.com/Moist-Cat/AIDScrapper/blob/main/help.txt
